server:
  port: 9003

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: openapi
          uri: http://localhost:9003/
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=user/(?<path>.*), /$\{path}
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**
          filters:
            - RewritePath=car/(?<path>.*), /$\{path}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=order/(?<path>.*), /$\{path}

springdoc:
  swagger-ui:
    urls:
      - name: user
        url: /user/v3/api-docs
      - name: car
        url: /car/v3/api-docs
      - name: order
        url: /order/v3/api-docs

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info, routes